### ISSUE TITLE
UserCamera begins stock in the floor.

### ISSUE THREAD

**Issue by ericgundrum** [jackwilliambell/squidhall#21]
The UserCamera vertical position specified in 'squidhall/world.module.json' (1.6m) is smaller than the default collision ellipsoid specified in 'squidspace.js' (radii 1m). This causes the camera to step up out of the floor when first moved.

**Comment by ericgundrum** [comment]
A quick fix is to change `UserCamera.position.y` from 1.6 to 2 in 'world.module.json'. However, 2 meters might be taller than we want for an avatar. I assume that is why the camera was set at 1.6m high.

Also, a 2m diameter collision sphere seems wrong. If we want to enforce social distancing, it should be bigger in the horizontal plane. If we want to allow typical attendees to get close to each other, the horizontal radii should be smaller. 

Maybe something like to {0.5, 0.8, 0.2} is closer to adult human form. How these values work with movement should be easier to see when we switch to planar avatars.

**Comment by jackwilliambell** [comment]
I'll add a card to Trello for this.

Jack

**Comment by jackwilliambell** [comment]
This is done.
